variables:
  KUBERNETES_CPU_REQUEST: '0.1'
  KUBERNETES_CPU_LIMIT: '0.1'
  KUBERNETES_MEMORY_REQUEST: 256M
  KUBERNETES_MEMORY_LIMIT: 256M

  S3_ENDPOINT: s3.amazonaws.com
  S3_REGION: us-west-1
  S3_BUCKET: bakery
  S3_ACCESS_KEY: <s3 access key>
  S3_SECRET_KEY: <s3 secret key>
  S3_SSL: 'true'
  CONTROLLER_URL: https://bakery.example.com
  LOG_FORMAT: simple
  BUILD_CPU: '1'
  BUILD_MEMORY: 5G
  DOCKER_CONFIG_DIRECTORY: /kaniko/.docker
  CONTEXT: '.'
  DOCKERFILE: Dockerfile
  NO_PUSH: 'false'
  COMPRESSED_CACHING: 'true'
  CACHE_ENABLE: 'true'

stages:
- build
- release

##############################################################################
##                               Build Image Template(hidden)               ##
##############################################################################
.buildTemplate: &buildTemplate
  stage: build
  image:
    name: docker.io/rayshoo/bakery-client:v1.0.1
    entrypoint: [""]
  script:
  - |
    cat > .env << EOF
    VERSION=$IMAGE_TAG
    EOF
  - |
    cat >> /config.yaml <<EOF
    global:
      platform: ecs
      cpu: ${BUILD_CPU}
      memory: ${BUILD_MEMORY}
      kaniko-credentials:
      - registry: ${CI_REGISTRY}
        username: ${CI_REGISTRY_USER}
        password: ${CI_REGISTRY_PASSWORD}
      - registry: cache.example.com
        username: ${CACHE_REGISTRY_USER}
        password: ${CACHE_REGISTRY_PASSWORD}
      kaniko:
        context-path: ${CONTEXT}
        dockerfile: ${DOCKERFILE}
        cache:
          enable: ${CACHE_ENABLE}
          repo: cache.example.com/${CI_PROJECT_PATH}
          ttl: 24h
        snapshot-mode: redo
        use-new-run: true
        cleanup: true
        ignore-path: [${IGNORE_PATHS}]
        extra-flags: '${BUILD_EXTRA_FLAGS}'
        destination: ${IMAGE_NAME}:${IMAGE_TAG}
    bake:
    - arch: amd64
    - arch: arm64
    EOF
    cat /config.yaml
    bakery-client -config /config.yaml -repo ${CI_PROJECT_DIR}

##############################################################################
##                               Build Image                                ##
##############################################################################
build:
  variables:
    IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  <<: *buildTemplate
  only:
  - master

##############################################################################
##                               Build Image Tag                            ##
##############################################################################
build_tag:
  rules:
  - if: $CI_COMMIT_TAG
  variables:
    IMAGE_NAME: ${CI_REGISTRY}/${CI_PROJECT_PATH}
    IMAGE_TAG: $CI_COMMIT_TAG
  <<: *buildTemplate

##############################################################################
##                               Release                                    ##
##############################################################################
release:
  stage: release
  rules:
  - if: $CI_COMMIT_TAG
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  script:
  - echo "running release job"
  variables:
    KUBERNETES_CPU_REQUEST: '0.2'
    KUBERNETES_CPU_LIMIT: '0.2'
    KUBERNETES_MEMORY_REQUEST: 10M
    KUBERNETES_MEMORY_LIMIT: 10M
  release:
    name: Release $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    description: $CI_COMMIT_MESSAGE
    ref: $CI_COMMIT_SHA
  needs:
  - build_tag